version: "3"
services:
  fluentd:
    container_name: fluentd
    image: psyoblade/data-engineer-intermediate-day2-fluentd
    user: fluent
    tty: true
    ports:
      - 9880:9880
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
